### ISSUE TITLE
Version Problem - Issues

### ISSUE THREAD

**Issue by jeffersonswartz** [vichu5101/versionrepo#1]
1. Since version type is a generic key for all versions we can have it as an enum
https://github.com/vichu5101/versionrepo/blob/ff1fda5da003d547665a5fc40efc68f21d33db54/version.ts#L17
For Example:
```typescript
enum VersionType {
    MAJOR,
    MINOR,
}

// Use it as
{
    ...
    versionType: UpdateType.MAJOR;
    ...
}
```

---

2. Instead of using `any` for the function parameters try to put the exact type we need for the param to be 
https://github.com/vichu5101/versionrepo/blob/ff1fda5da003d547665a5fc40efc68f21d33db54/version.ts#L71

---

### Summary

---

- Good job on following the naming conventions, spacing and indentation.
- The code quality is nice and very readable, Keep following this.
- Learn more about Array methods and try to improve this further.

**Comment by vishnu-varthanan** [comment]
Thank you for your response Sir, and I figured out the corrections and
cleared it that you said that I have to Change in Version Problem. Kindly
revisit Sir, Thank you 😊.
